apiVersion: v2
name: ingress-nginx-external
version: 1.0.0
description: "ingress-nginx-external"
type: application
maintainers:
  - name: FZEN
    email: admin@fzen.pro
    url: https://fzen.pro
appVersion: 1.0.0
dependencies:
  - name: ingress-nginx
    version: ">=0.0.0"
    repository: 'https://kubernetes.github.io/ingress-nginx'